package fiscal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PermissaoOperador generated by hbm2java
 */
@Entity
@Table(name="TBPERMISSAO_OPERADOR")
public class FiscalPermissaoOperador  implements java.io.Serializable {


     private Long id;
     private FiscalUsuario usuario;
     private FiscalFuncionalidade funcionalidade;
     private Boolean ler;
     private Boolean gravar;
     private Boolean excluir;

    public FiscalPermissaoOperador() {
    }


    public FiscalPermissaoOperador(Long id, FiscalUsuario usuario, FiscalFuncionalidade funcionalidade) {
        this.id = id;
        this.usuario = usuario;
        this.funcionalidade = funcionalidade;
    }
    public FiscalPermissaoOperador(Long id, FiscalUsuario usuario, FiscalFuncionalidade funcionalidade, Boolean ler, Boolean gravar, Boolean excluir) {
       this.id = id;
       this.usuario = usuario;
       this.funcionalidade = funcionalidade;
       this.ler = ler;
       this.gravar = gravar;
       this.excluir = excluir;
    }

     @Id

    @Column(name="PERMISSAO_OPERADOR_ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USUARIO_ID", nullable=false)
    public  FiscalUsuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(FiscalUsuario usuario) {
        this.usuario = usuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FUNCIONALIDADE_ID", nullable=false)
    public FiscalFuncionalidade getFuncionalidade() {
        return this.funcionalidade;
    }

    public void setFuncionalidade(FiscalFuncionalidade funcionalidade) {
        this.funcionalidade = funcionalidade;
    }

    @Column(name="LER", precision=1, scale=0)
    public Boolean getLer() {
        return this.ler;
    }

    public void setLer(Boolean ler) {
        this.ler = ler;
    }

    @Column(name="GRAVAR", precision=1, scale=0)
    public Boolean getGravar() {
        return this.gravar;
    }

    public void setGravar(Boolean gravar) {
        this.gravar = gravar;
    }

    @Column(name="EXCLUIR", precision=1, scale=0)
    public Boolean getExcluir() {
        return this.excluir;
    }

    public void setExcluir(Boolean excluir) {
        this.excluir = excluir;
    }



  // The following is extra code specified in the hbm.xml files
    private static final long serialVersionUID = 1L;
  // end of extra code specified in the hbm.xml files

}


