package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Imagem generated by hbm2java
 */
@Entity
@Table(name = "TBIMAGEM")
public class FiscalImagem implements java.io.Serializable {

	private Long id;
	private String nome;
	private String diretorioImagem;
	private List<FiscalTrafego> trafegos = new ArrayList<FiscalTrafego>(0);

	public FiscalImagem() {

	}

	public FiscalImagem(Long id, String nome, String diretorioImagem) {
		this.id = id;
		this.nome = nome;
		this.diretorioImagem = diretorioImagem;
	}

	public FiscalImagem(Long id, String nome, String diretorioImagem, List<FiscalTrafego> trafegos) {
		this.id = id;
		this.nome = nome;
		this.diretorioImagem = diretorioImagem;
		this.trafegos = trafegos;
	}

	@Id
	@GeneratedValue
	@Column(name = "IMAGEM_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NOME", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "DIRETORIO_IMAGEM", nullable = false, length = 100)
	public String getDiretorioImagem() {
		return this.diretorioImagem;
	}

	public void setDiretorioImagem(String diretorioImagem) {
		this.diretorioImagem = diretorioImagem;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imagem")
	public List<FiscalTrafego> getTrafegos() {
		return this.trafegos;
	}

	public void setTrafegos(List<FiscalTrafego> trafegos) {
		this.trafegos = trafegos;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
