package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ResponsavelVeiculo generated by hbm2java
 */
@Entity
@Table(name = "TBRESPONSAVEL_VEICULO")
public class FiscalResponsavelVeiculo implements java.io.Serializable {

	private Long id;
	private String nome;
	private String descricao;
	private String numeroDocumento;
	private List<FiscalVeiculoCuidadoEspecial> veiculoCuidadoEspecials = new ArrayList<FiscalVeiculoCuidadoEspecial>(0);

	public FiscalResponsavelVeiculo() {
	}

	public FiscalResponsavelVeiculo(Long id) {
		this.id = id;
	}

	public FiscalResponsavelVeiculo(Long id, String nome, String descricao, String numeroDocumento,
			List<FiscalVeiculoCuidadoEspecial> veiculoCuidadoEspecials) {
		this.id = id;
		this.nome = nome;
		this.descricao = descricao;
		this.numeroDocumento = numeroDocumento;
		this.veiculoCuidadoEspecials = veiculoCuidadoEspecials;
	}

	@Id
	@GeneratedValue
	@Column(name = "RESPONSAVEL_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NOME", length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "DESCRICAO", length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "NUMERO_DOCUMENTO", length = 50)
	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "responsavelVeiculo")
	public List<FiscalVeiculoCuidadoEspecial> getVeiculoCuidadoEspecials() {
		return this.veiculoCuidadoEspecials;
	}

	public void setVeiculoCuidadoEspecials(List<FiscalVeiculoCuidadoEspecial> veiculoCuidadoEspecials) {
		this.veiculoCuidadoEspecials = veiculoCuidadoEspecials;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
