package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoServico generated by hbm2java
 */
@Entity
@Table(name = "TBTIPO_SERVICO")
public class FiscalTipoServico implements java.io.Serializable {

	private Long id;
	private String nome;
	private String descricao;
	private List<FiscalEquipamentoServico> equipamentoServicos = new ArrayList<FiscalEquipamentoServico>(0);

	public FiscalTipoServico() {
	}

	public FiscalTipoServico(Long id) {
		this.id = id;
	}

	public FiscalTipoServico(Long id, String nome, String descricao, List<FiscalEquipamentoServico> equipamentoServicos) {
		this.id = id;
		this.nome = nome;
		this.descricao = descricao;
		this.equipamentoServicos = equipamentoServicos;
	}

	@Id
	@GeneratedValue
	@Column(name = "TIPO_SERVICO_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NOME", length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "DESCRICAO", length = 50)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoServico")
	public List<FiscalEquipamentoServico> getEquipamentoServicos() {
		return this.equipamentoServicos;
	}

	public void setEquipamentoServicos(List<FiscalEquipamentoServico> equipamentoServicos) {
		this.equipamentoServicos = equipamentoServicos;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
