package fiscal;

// Generated 17/08/2007 09:44:48 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Funcionalidade generated by hbm2java
 */
@Entity
@Table(name = "TBFUNCIONALIDADE")
public class FiscalFuncionalidade implements java.io.Serializable {

	private Long id;
	private FiscalFuncionalidade funcionalidade;
	private String descricao;
	private String url;
	private BigDecimal sequencia;
	private List<FiscalFuncionalidade> funcionalidades = new ArrayList<FiscalFuncionalidade>(0);
	private List<FiscalPermissaoPerfil> permissaoPerfils = new ArrayList<FiscalPermissaoPerfil>(0);
	private List<FiscalPermissaoOperador> permissaoOperadors = new ArrayList<FiscalPermissaoOperador>(0);

	public FiscalFuncionalidade() {
	}

	public FiscalFuncionalidade(Long id, String descricao) {
		this.id = id;
		this.descricao = descricao;
	}

	public FiscalFuncionalidade(Long id, FiscalFuncionalidade funcionalidade, String descricao, String url, BigDecimal sequencia,
			List<FiscalFuncionalidade> funcionalidades, List<FiscalPermissaoPerfil> permissaoPerfils,
			List<FiscalPermissaoOperador> permissaoOperadors) {
		this.id = id;
		this.funcionalidade = funcionalidade;
		this.descricao = descricao;
		this.url = url;
		this.sequencia = sequencia;
		this.funcionalidades = funcionalidades;
		this.permissaoPerfils = permissaoPerfils;
		this.permissaoOperadors = permissaoOperadors;
	}

	@Id
	@GeneratedValue
	@Column(name = "FUNCIONALIDADE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FUNCIONALIDADE_PAI")
	public FiscalFuncionalidade getFuncionalidade() {
		return this.funcionalidade;
	}

	public void setFuncionalidade(FiscalFuncionalidade funcionalidade) {
		this.funcionalidade = funcionalidade;
	}

	@Column(name = "NOME", nullable = false, length = 60)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "URL")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "SEQUENCIA", precision = 22, scale = 0)
	public BigDecimal getSequencia() {
		return this.sequencia;
	}

	public void setSequencia(BigDecimal sequencia) {
		this.sequencia = sequencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcionalidade")
	public List<FiscalFuncionalidade> getFuncionalidades() {
		return this.funcionalidades;
	}

	public void setFuncionalidades(List<FiscalFuncionalidade> funcionalidades) {
		this.funcionalidades = funcionalidades;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcionalidade")
	public List<FiscalPermissaoPerfil> getPermissaoPerfils() {
		return this.permissaoPerfils;
	}

	public void setPermissaoPerfils(List<FiscalPermissaoPerfil> permissaoPerfils) {
		this.permissaoPerfils = permissaoPerfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcionalidade")
	public List<FiscalPermissaoOperador> getPermissaoOperadors() {
		return this.permissaoOperadors;
	}

	public void setPermissaoOperadors(List<FiscalPermissaoOperador> permissaoOperadors) {
		this.permissaoOperadors = permissaoOperadors;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
