package fiscal;

// Generated 17/08/2007 09:44:48 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Participante generated by hbm2java
 */
@Entity
@Table(name = "TBPARTICIPANTE")
public class FiscalParticipante implements java.io.Serializable {

	private Long id;
	private FiscalUsuario usuario;
	private FiscalPerfil perfil;

	public FiscalParticipante() {
	}

	public FiscalParticipante(Long id, FiscalUsuario usuario, FiscalPerfil perfil) {
		this.id = id;
		this.usuario = usuario;
		this.perfil = perfil;
	}

	@Id
	@GeneratedValue
	@Column(name = "PARTICIPANTE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUARIO_ID", nullable = false)
	public FiscalUsuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(FiscalUsuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERFIL_ID", nullable = false)
	public FiscalPerfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(FiscalPerfil perfil) {
		this.perfil = perfil;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
