package fiscal;
// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9


    
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Alerta generated by hbm2java
 */
@Entity
@Table(name="TBALERTA"
)
public class FiscalAlerta  implements java.io.Serializable {


     private Long id;
     private String nome;
     private String descricao;
     private String mensagem;
     private Long status;
     private List<FiscalTicket> tickets = new ArrayList<FiscalTicket>(0);

    public FiscalAlerta() {
    }

	
    public FiscalAlerta(Long id) {
        this.id = id;
    }
    public FiscalAlerta(Long id, String nome, String descricao, String mensagem, Long status, List<FiscalTicket> tickets) {
       this.id = id;
       this.nome = nome;
       this.descricao = descricao;
       this.mensagem = mensagem;
       this.status = status;
       this.tickets = tickets;
    }
   
     @Id 
     @GeneratedValue
    
    @Column(name="ALERTA_ID", unique=true, nullable=false, precision=38, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="NOME", length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name="DESCRICAO", length=100)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    @Column(name="MENSAGEM", length=50)
    public String getMensagem() {
        return this.mensagem;
    }
    
    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }
    
    @Column(name="STATUS", precision=38, scale=0)
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
@OneToMany(     fetch=FetchType.LAZY, mappedBy="alerta")
    public List<FiscalTicket> getTickets() {
        return this.tickets;
    }
    
    public void setTickets(List<FiscalTicket> tickets) {
        this.tickets = tickets;
    }



  // The following is extra code specified in the hbm.xml files
    private static final long serialVersionUID = 1L;
  // end of extra code specified in the hbm.xml files

}


