package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Permissao generated by hbm2java
 */
@Entity
@Table(name = "TBPERMISSAO")
public class FiscalPermissao implements java.io.Serializable {

	private Long id;
	private FiscalPerfil perfil;
	private FiscalFuncionalidade funcionalidade;
	private Long situacao;

	public FiscalPermissao() {
	}

	public FiscalPermissao(Long id, FiscalPerfil perfil, FiscalFuncionalidade funcionalidade, Long situacao) {
		this.id = id;
		this.perfil = perfil;
		this.funcionalidade = funcionalidade;
		this.situacao = situacao;
	}

	@Id
	@GeneratedValue
	@Column(name = "PERMISSAO_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERFIL_ID", nullable = false)
	public FiscalPerfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(FiscalPerfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FUNCIONALIDADE_ID", nullable = false)
	public FiscalFuncionalidade getFuncionalidade() {
		return this.funcionalidade;
	}

	public void setFuncionalidade(FiscalFuncionalidade funcionalidade) {
		this.funcionalidade = funcionalidade;
	}

	@Column(name = "SITUACAO", nullable = false, precision = 38, scale = 0)
	public Long getSituacao() {
		return this.situacao;
	}

	public void setSituacao(Long situacao) {
		this.situacao = situacao;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
