package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "TBPERFIL")
public class FiscalPerfil implements java.io.Serializable {

	private Long id;
	private String descricao;
	private String nome;

	@Column(name = "NOME")
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	private List<FiscalParticipante> participantes = new ArrayList<FiscalParticipante>(0);
	private List<FiscalPermissaoPerfil> permissaoPerfils = new ArrayList<FiscalPermissaoPerfil>(0);

	public FiscalPerfil() {
	}

	public FiscalPerfil(Long id, String descricao) {
		this.id = id;
		this.descricao = descricao;
	}

	public FiscalPerfil(Long id, String descricao, List<FiscalParticipante> participantes, List<FiscalPermissaoPerfil> permissaoPerfils) {
		this.id = id;
		this.descricao = descricao;
		this.participantes = participantes;
		this.permissaoPerfils = permissaoPerfils;
	}

	public FiscalPerfil(Long id) {
		this.id = id;
	}

	@Id
	@GeneratedValue
	@Column(name = "PERFIL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public List<FiscalParticipante> getParticipantes() {
		return this.participantes;
	}

	public void setParticipantes(List<FiscalParticipante> participantes) {
		this.participantes = participantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public List<FiscalPermissaoPerfil> getPermissaoPerfils() {
		return this.permissaoPerfils;
	}

	public void setPermissaoPerfils(List<FiscalPermissaoPerfil> permissaoPerfils) {
		this.permissaoPerfils = permissaoPerfils;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
