package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MensagemAdHoc generated by hbm2java
 */
@Entity
@Table(name = "TBMENSAGEM_AD_HOC")
public class FiscalMensagemAdHoc implements java.io.Serializable {

	private Long id;
	private FiscalEquipamento equipamento;
	private FiscalUsuario usuario;
	private String mensagem;
	private Date dataInicio;
	private Date dataFim;

	public FiscalMensagemAdHoc() {
	}

	public FiscalMensagemAdHoc(Long id, FiscalEquipamento equipamento, FiscalUsuario usuario, String mensagem) {
		this.id = id;
		this.equipamento = equipamento;
		this.usuario = usuario;
		this.mensagem = mensagem;
	}

	public FiscalMensagemAdHoc(Long id, FiscalEquipamento equipamento, FiscalUsuario usuario, String mensagem, Date dataInicio,
			Date dataFim) {
		this.id = id;
		this.equipamento = equipamento;
		this.usuario = usuario;
		this.mensagem = mensagem;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
	}

	@Id
	@GeneratedValue
	@Column(name = "MENSAGEM_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EQUIPAMENTO_DESTINO_ID", nullable = false)
	public FiscalEquipamento getEquipamento() {
		return this.equipamento;
	}

	public void setEquipamento(FiscalEquipamento equipamento) {
		this.equipamento = equipamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUARIO_ID", nullable = false)
	public FiscalUsuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(FiscalUsuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "MENSAGEM", nullable = false, length = 10)
	public String getMensagem() {
		return this.mensagem;
	}

	public void setMensagem(String mensagem) {
		this.mensagem = mensagem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_INICIO")
	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_FIM")
	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
