package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VeiculoCuidadoEspecial generated by hbm2java
 */
@Entity
@Table(name = "TBTICKET_MOTIVO")
public class FiscalTicketMotivo implements java.io.Serializable {

	private Long id;
	private FiscalTicket ticket;
	private FiscalMotivo motivo;

	public FiscalTicketMotivo() {
	}

	public FiscalTicketMotivo(Long id, FiscalTicket ticket, FiscalMotivo motivo) {
		this.id = id;
		this.ticket = ticket;
		this.motivo = motivo;
	}

	@Id
	@GeneratedValue
	@Column(name = "TICKET_MOTIVO_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TICKET_ID", nullable = false)
	public FiscalTicket getTicket() {
		return ticket;
	}

	public void setTicket(FiscalTicket ticket) {
		this.ticket = ticket;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOTIVO_ID")
	public FiscalMotivo getMotivo() {
		return motivo;
	}

	public void setMotivo(FiscalMotivo motivo) {
		this.motivo = motivo;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}