package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Local generated by hbm2java
 */
@Entity
@Table(name = "TBLOCAL")
public class FiscalLocal implements java.io.Serializable {

	private Long id;
	private String codigoLocal;
	private String logradouro;
	private Double distanciaKmPosto;
	private Long qtdeFaixa;
	private String nome;
	private String descricao;
	private List<FiscalEquipamentoFaixa> equipamentoFaixas = new ArrayList<FiscalEquipamentoFaixa>(0);

	public FiscalLocal() {
	}

	public FiscalLocal(Long id) {
		this.id = id;
	}

	public FiscalLocal(Long id, String codigoLocal, String logradouro, Double distanciaKmPosto, Long qtdeFaixa,
			List<FiscalEquipamentoFaixa> equipamentoFaixas, String nome, String descricao) {
		this.id = id;
		this.codigoLocal = codigoLocal;
		this.logradouro = logradouro;
		this.distanciaKmPosto = distanciaKmPosto;
		this.qtdeFaixa = qtdeFaixa;
		this.equipamentoFaixas = equipamentoFaixas;
		this.nome = nome;
		this.descricao = descricao;
	}

	@Id
	@GeneratedValue
	@Column(name = "LOCAL_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CODIGO_LOCAL", length = 50)
	public String getCodigoLocal() {
		return this.codigoLocal;
	}

	public void setCodigoLocal(String codigoLocal) {
		this.codigoLocal = codigoLocal;
	}

	@Column(name = "LOGRADOURO", length = 100)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "DISTANCIA_KM_POSTO", precision = 50, scale = 0)
	public Double getDistanciaKmPosto() {
		return this.distanciaKmPosto;
	}

	public void setDistanciaKmPosto(Double distanciaKmPosto) {
		this.distanciaKmPosto = distanciaKmPosto;
	}

	@Column(name = "QTDE_FAIXA", precision = 38, scale = 0)
	public Long getQtdeFaixa() {
		return this.qtdeFaixa;
	}

	public void setQtdeFaixa(Long qtdeFaixa) {
		this.qtdeFaixa = qtdeFaixa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "local")
	public List<FiscalEquipamentoFaixa> getEquipamentoFaixas() {
		return this.equipamentoFaixas;
	}

	public void setEquipamentoFaixas(List<FiscalEquipamentoFaixa> equipamentoFaixas) {
		this.equipamentoFaixas = equipamentoFaixas;
	}

	@Column(name = "NOME", length = 50)
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "DESCRICAO", length = 100)
	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
