package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VeiculoCuidadoEspecial generated by hbm2java
 */
@Entity
@Table(name = "TBVEICULO_CUIDADO_ESPECIAL")
public class FiscalVeiculoCuidadoEspecial implements java.io.Serializable {

	private Long id;
	private FiscalResponsavelVeiculo responsavelVeiculo;
	private FiscalCuidadoEspecial cuidadoEspecial;
	private FiscalVeiculo veiculo;
	private Date dataInicio;
	private Date dataFim;

	public FiscalVeiculoCuidadoEspecial() {
	}

	public FiscalVeiculoCuidadoEspecial(Long id, FiscalCuidadoEspecial cuidadoEspecial, FiscalVeiculo veiculo) {
		this.id = id;
		this.cuidadoEspecial = cuidadoEspecial;
		this.veiculo = veiculo;
	}

	public FiscalVeiculoCuidadoEspecial(Long id, FiscalResponsavelVeiculo responsavelVeiculo, FiscalCuidadoEspecial cuidadoEspecial,
			FiscalVeiculo veiculo, Date dataInicio, Date dataFim) {
		this.id = id;
		this.responsavelVeiculo = responsavelVeiculo;
		this.cuidadoEspecial = cuidadoEspecial;
		this.veiculo = veiculo;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
	}

	@Id
	@GeneratedValue
	@Column(name = "VEICULO_CUIDADO_ESPECIAL_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESPONSAVEL_ID")
	public FiscalResponsavelVeiculo getResponsavelVeiculo() {
		return this.responsavelVeiculo;
	}

	public void setResponsavelVeiculo(FiscalResponsavelVeiculo responsavelVeiculo) {
		this.responsavelVeiculo = responsavelVeiculo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CUIDADO_ESPECIAL_ID", nullable = false)
	public FiscalCuidadoEspecial getCuidadoEspecial() {
		return this.cuidadoEspecial;
	}

	public void setCuidadoEspecial(FiscalCuidadoEspecial cuidadoEspecial) {
		this.cuidadoEspecial = cuidadoEspecial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VEICULO_ID", nullable = false)
	public FiscalVeiculo getVeiculo() {
		return this.veiculo;
	}

	public void setVeiculo(FiscalVeiculo veiculo) {
		this.veiculo = veiculo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_INICIO")
	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_FIM")
	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
