package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CuidadoEspecial generated by hbm2java
 */
@Entity
@Table(name = "TBCUIDADO_ESPECIAL")
public class FiscalCuidadoEspecial implements java.io.Serializable {

	private Long id;
	private FiscalAcaoCuidadoEspecial acaoCuidadoEspecial;
	private FiscalTipoMercadoria tipoMercadoria;
	private String nome;
	private String descricao;
	private String mensagem;
	private List<FiscalVeiculoCuidadoEspecial> veiculoCuidadoEspecials = new ArrayList<FiscalVeiculoCuidadoEspecial>(0);

	public FiscalCuidadoEspecial() {
	}

	public FiscalCuidadoEspecial(Long id, FiscalAcaoCuidadoEspecial acaoCuidadoEspecial, String nome) {
		this.id = id;
		this.acaoCuidadoEspecial = acaoCuidadoEspecial;
		this.nome = nome;
	}

	public FiscalCuidadoEspecial(Long id, FiscalAcaoCuidadoEspecial acaoCuidadoEspecial, FiscalTipoMercadoria tipoMercadoria,
			String nome, String descricao, String mensagem, List<FiscalVeiculoCuidadoEspecial> veiculoCuidadoEspecials) {
		this.id = id;
		this.acaoCuidadoEspecial = acaoCuidadoEspecial;
		this.tipoMercadoria = tipoMercadoria;
		this.nome = nome;
		this.descricao = descricao;
		this.mensagem = mensagem;
		this.veiculoCuidadoEspecials = veiculoCuidadoEspecials;
	}

	@Id
	@GeneratedValue
	@Column(name = "CUIDADO_ESPECIAL_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACAO_CUIDADO_ESPECIAL_ID", nullable = false)
	public FiscalAcaoCuidadoEspecial getAcaoCuidadoEspecial() {
		return this.acaoCuidadoEspecial;
	}

	public void setAcaoCuidadoEspecial(FiscalAcaoCuidadoEspecial acaoCuidadoEspecial) {
		this.acaoCuidadoEspecial = acaoCuidadoEspecial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_MERCADORIA_ID")
	public FiscalTipoMercadoria getTipoMercadoria() {
		return this.tipoMercadoria;
	}

	public void setTipoMercadoria(FiscalTipoMercadoria tipoMercadoria) {
		this.tipoMercadoria = tipoMercadoria;
	}

	@Column(name = "NOME", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "DESCRICAO", length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "MENSAGEM", length = 50)
	public String getMensagem() {
		return this.mensagem;
	}

	public void setMensagem(String mensagem) {
		this.mensagem = mensagem;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuidadoEspecial")
	public List<FiscalVeiculoCuidadoEspecial> getVeiculoCuidadoEspecials() {
		return this.veiculoCuidadoEspecials;
	}

	public void setVeiculoCuidadoEspecials(List<FiscalVeiculoCuidadoEspecial> veiculoCuidadoEspecials) {
		this.veiculoCuidadoEspecials = veiculoCuidadoEspecials;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
