package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoUnidadeFiscal generated by hbm2java
 */
@Entity
@Table(name = "TBTIPO_UNIDADE_FISCAL")
public class FiscalTipoUnidadeFiscal implements java.io.Serializable {

	private Long id;
	private String nome;
	private String descricao;
	private List<FiscalUnidadeFiscal> unidadeFiscals = new ArrayList<FiscalUnidadeFiscal>(0);

	public FiscalTipoUnidadeFiscal() {
	}

	public FiscalTipoUnidadeFiscal(Long id) {
		this.id = id;
	}

	public FiscalTipoUnidadeFiscal(Long id, String nome) {
		this.id = id;
		this.nome = nome;
	}

	public FiscalTipoUnidadeFiscal(Long id, String nome, String descricao, List<FiscalUnidadeFiscal> unidadeFiscals) {
		this.id = id;
		this.nome = nome;
		this.descricao = descricao;
		this.unidadeFiscals = unidadeFiscals;
	}

	@Id
	@GeneratedValue
	@Column(name = "TIPO_UNIDADE_FISCAL_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NOME", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "DESCRICAO", length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUnidadeFiscal")
	public List<FiscalUnidadeFiscal> getUnidadeFiscals() {
		return this.unidadeFiscals;
	}

	public void setUnidadeFiscals(List<FiscalUnidadeFiscal> unidadeFiscals) {
		this.unidadeFiscals = unidadeFiscals;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
