package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEquipamento generated by hbm2java
 */
@Entity
@Table(name = "TBTIPO_EQUIPAMENTO")
public class FiscalTipoEquipamento implements java.io.Serializable {

	private Long id;
	private String nome;
	private String descricao;
	private List<FiscalEquipamento> equipamentos = new ArrayList<FiscalEquipamento>(0);

	public FiscalTipoEquipamento() {
	}

	public FiscalTipoEquipamento(Long id) {
		this.id = id;
	}

	public FiscalTipoEquipamento(Long id, String nome) {
		this.id = id;
		this.nome = nome;
	}

	public FiscalTipoEquipamento(Long id, String nome, String descricao, List<FiscalEquipamento> equipamentos) {
		this.id = id;
		this.nome = nome;
		this.descricao = descricao;
		this.equipamentos = equipamentos;
	}

	@Id
	@GeneratedValue
	@Column(name = "TIPO_EQUIPAMENTO_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NOME", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "DESCRICAO", length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoEquipamento")
	public List<FiscalEquipamento> getEquipamentos() {
		return this.equipamentos;
	}

	public void setEquipamentos(List<FiscalEquipamento> equipamentos) {
		this.equipamentos = equipamentos;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
