package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Equipamento generated by hbm2java
 */
@Entity
@Table(name = "TBEQUIPAMENTO")
public class FiscalEquipamento implements java.io.Serializable {

	private Long id;
	private FiscalTipoEquipamento tipoEquipamento;
	private String nome;
	private String equipamentoCodigo;
	private List<FiscalEquipamentoServico> equipamentoServicos = new ArrayList<FiscalEquipamentoServico>(0);
	private List<FiscalMensagemAdHoc> mensagemAdHocs = new ArrayList<FiscalMensagemAdHoc>(0);
	private List<FiscalEquipamentoFaixa> equipamentoFaixas = new ArrayList<FiscalEquipamentoFaixa>(0);

	public FiscalEquipamento() {
	}

	public FiscalEquipamento(Long id, FiscalTipoEquipamento tipoEquipamento) {
		this.id = id;
		this.tipoEquipamento = tipoEquipamento;
	}

	public FiscalEquipamento(Long id, FiscalTipoEquipamento tipoEquipamento, String nome, String equipamentoCodigo,
			List<FiscalEquipamentoServico> equipamentoServicos, List<FiscalMensagemAdHoc> mensagemAdHocs,
			List<FiscalEquipamentoFaixa> equipamentoFaixas) {
		this.id = id;
		this.tipoEquipamento = tipoEquipamento;
		this.nome = nome;
		this.equipamentoCodigo = equipamentoCodigo;
		this.equipamentoServicos = equipamentoServicos;
		this.mensagemAdHocs = mensagemAdHocs;
		this.equipamentoFaixas = equipamentoFaixas;
	}

	@Id
	@GeneratedValue
	@Column(name = "EQUIPAMENTO_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_EQUIPAMENTO_ID", nullable = false)
	public FiscalTipoEquipamento getTipoEquipamento() {
		return this.tipoEquipamento;
	}

	public void setTipoEquipamento(FiscalTipoEquipamento tipoEquipamento) {
		this.tipoEquipamento = tipoEquipamento;
	}

	@Column(name = "NOME", length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "EQUIPAMENTO_CODIGO", length = 50)
	public String getEquipamentoCodigo() {
		return this.equipamentoCodigo;
	}

	public void setEquipamentoCodigo(String equipamentoCodigo) {
		this.equipamentoCodigo = equipamentoCodigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipamento")
	public List<FiscalEquipamentoServico> getEquipamentoServicos() {
		return this.equipamentoServicos;
	}

	public void setEquipamentoServicos(List<FiscalEquipamentoServico> equipamentoServicos) {
		this.equipamentoServicos = equipamentoServicos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipamento")
	public List<FiscalMensagemAdHoc> getMensagemAdHocs() {
		return this.mensagemAdHocs;
	}

	public void setMensagemAdHocs(List<FiscalMensagemAdHoc> mensagemAdHocs) {
		this.mensagemAdHocs = mensagemAdHocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipamento")
	public List<FiscalEquipamentoFaixa> getEquipamentoFaixas() {
		return this.equipamentoFaixas;
	}

	public void setEquipamentoFaixas(List<FiscalEquipamentoFaixa> equipamentoFaixas) {
		this.equipamentoFaixas = equipamentoFaixas;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
