package fiscal;

// Generated 10/07/2009 10:49:54 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Eixo generated by hbm2java
 */
@Entity
@Table(name = "TBEIXO")
public class FiscalEixo implements java.io.Serializable {

	private Long id;
	private FiscalTrafego trafego;
	private Long numeroEixo;
	private Double distanciaProximoEixo;
	private Double pesoEixo;
	private Double pesoAbsoluto;

	public FiscalEixo() {
	}

	public FiscalEixo(Long id, FiscalTrafego trafego) {
		this.id = id;
		this.trafego = trafego;
	}

	public FiscalEixo(Long id, FiscalTrafego trafego, Long numeroEixo, Double distanciaProximoEixo, Double pesoEixo) {
		this.id = id;
		this.trafego = trafego;
		this.numeroEixo = numeroEixo;
		this.distanciaProximoEixo = distanciaProximoEixo;
		this.pesoEixo = pesoEixo;
	}

	@Id
	@GeneratedValue
	@Column(name = "EIXO_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRAFEGO_ID", nullable = false)
	public FiscalTrafego getTrafego() {
		return this.trafego;
	}

	public void setTrafego(FiscalTrafego trafego) {
		this.trafego = trafego;
	}

	@Column(name = "NUMERO_EIXO", precision = 38, scale = 0)
	public Long getNumeroEixo() {
		return this.numeroEixo;
	}

	public void setNumeroEixo(Long numeroEixo) {
		this.numeroEixo = numeroEixo;
	}

	@Column(name = "DISTANCIA_PROXIMO_EIXO", precision = 50, scale = 0)
	public Double getDistanciaProximoEixo() {
		return this.distanciaProximoEixo;
	}

	public void setDistanciaProximoEixo(Double distanciaProximoEixo) {
		this.distanciaProximoEixo = distanciaProximoEixo;
	}

	@Column(name = "PESO_EIXO", precision = 50, scale = 0)
	public Double getPesoEixo() {
		return this.pesoEixo;
	}

	public void setPesoEixo(Double pesoEixo) {
		this.pesoEixo = pesoEixo;
	}

	@Column(name = "PESO_ABSOLUTO_SIWIM", precision = 50, scale = 0)
	public Double getPesoAbsoluto() {
		return pesoAbsoluto;
	}

	public void setPesoAbsoluto(Double pesoAbsoluto) {
		this.pesoAbsoluto = pesoAbsoluto;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
